import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join, resolve } from "node:path";

import type { DoctorCheck, DoctorReport, DoctorStatus } from "./doctor.js";
import { summarizeDoctorStatus } from "./doctor.js";

export interface ProjectDoctorOptions {
  cwd?: string;
}

interface GeneratedManifest {
  generator?: { name?: string; version?: string };
  app?: { name?: string; identifier?: string };
  source?: { url?: string };
  packageManager?: "bun" | "npm";
  icon?: { png?: string; ico?: string; macIconset?: string; sourceUrl?: string };
}

export function runProjectDoctor(options: ProjectDoctorOptions = {}): DoctorReport {
  const root = resolve(options.cwd ?? process.cwd());
  const manifest = readGeneratedManifest(root);
  const checks = [
    checkGeneratedManifest(root, manifest),
    checkPackageJson(root, manifest),
    checkElectrobunConfig(root),
    checkMainview(root),
    checkIconAssets(root, manifest),
    checkDmgScript(root),
    checkBuildOutput(root),
  ];

  return {
    status: summarizeDoctorStatus(checks),
    platform: `project ${root}`,
    checks,
  };
}

function readGeneratedManifest(root: string): GeneratedManifest | undefined {
  const path = join(root, "appbun.generated.json");
  if (!existsSync(path)) {
    return undefined;
  }

  try {
    return JSON.parse(readFileSync(path, "utf8")) as GeneratedManifest;
  } catch {
    return undefined;
  }
}

function checkGeneratedManifest(root: string, manifest?: GeneratedManifest): DoctorCheck {
  const path = join(root, "appbun.generated.json");
  if (!existsSync(path)) {
    return {
      name: "Generated manifest",
      status: "fail",
      message: "appbun.generated.json not found",
      detail: "Run this command from a generated appbun project root.",
    };
  }

  if (!manifest) {
    return {
      name: "Generated manifest",
      status: "fail",
      message: "appbun.generated.json could not be parsed",
    };
  }

  return {
    name: "Generated manifest",
    status: "ok",
    message: `${manifest.app?.name ?? "appbun app"} from ${manifest.source?.url ?? "unknown URL"}`,
    detail: `generated by ${manifest.generator?.name ?? "appbun"} ${manifest.generator?.version ?? "unknown version"}`,
  };
}

function checkPackageJson(root: string, manifest?: GeneratedManifest): DoctorCheck {
  const path = join(root, "package.json");
  if (!existsSync(path)) {
    return {
      name: "Package scripts",
      status: "fail",
      message: "package.json not found",
    };
  }

  try {
    const packageJson = JSON.parse(readFileSync(path, "utf8")) as { scripts?: Record<string, string> };
    const scripts = packageJson.scripts ?? {};
    const missing = ["dev", "build", "build:dmg", "build:macos", "build:windows", "build:linux"]
      .filter((script) => !scripts[script]);
    if (missing.length > 0) {
      return {
        name: "Package scripts",
        status: "fail",
        message: `missing ${missing.join(", ")}`,
      };
    }

    return {
      name: "Package scripts",
      status: "ok",
      message: `${manifest?.packageManager ?? "package manager"} scripts ready`,
    };
  } catch {
    return {
      name: "Package scripts",
      status: "fail",
      message: "package.json could not be parsed",
    };
  }
}

function checkElectrobunConfig(root: string): DoctorCheck {
  return existsSync(join(root, "electrobun.config.ts"))
    ? { name: "Electrobun config", status: "ok", message: "electrobun.config.ts found" }
    : { name: "Electrobun config", status: "fail", message: "electrobun.config.ts not found" };
}

function checkMainview(root: string): DoctorCheck {
  const missing = ["index.html", "index.css", "index.ts"]
    .filter((file) => !existsSync(join(root, "src", "mainview", file)));
  if (missing.length > 0) {
    return {
      name: "Local shell",
      status: "fail",
      message: `missing src/mainview/${missing.join(", src/mainview/")}`,
    };
  }

  return {
    name: "Local shell",
    status: "ok",
    message: "mainview shell files found",
  };
}

function checkIconAssets(root: string, manifest?: GeneratedManifest): DoctorCheck {
  const icon = manifest?.icon;
  if (!icon?.png && !icon?.ico && !icon?.macIconset) {
    return {
      name: "Icon assets",
      status: "warn",
      message: "no generated icon paths recorded",
      detail: "The app can still build, but platform packages may use default icons.",
    };
  }

  const missing = [icon.png, icon.ico, icon.macIconset]
    .filter((path): path is string => Boolean(path))
    .filter((path) => !existsSync(join(root, path)));

  if (missing.length > 0) {
    return {
      name: "Icon assets",
      status: "warn",
      message: `missing ${missing.join(", ")}`,
    };
  }

  return {
    name: "Icon assets",
    status: "ok",
    message: icon.sourceUrl ? `resolved from ${icon.sourceUrl}` : "fallback icon assets ready",
  };
}

function checkDmgScript(root: string): DoctorCheck {
  const path = join(root, "scripts", "create-dmg.mjs");
  if (!existsSync(path)) {
    return {
      name: "DMG script",
      status: "fail",
      message: "scripts/create-dmg.mjs not found",
    };
  }

  const source = readFileSync(path, "utf8");
  const supportsSigning = source.includes("APPLE_SIGN_IDENTITY");
  const supportsNotarization = source.includes("APPLE_NOTARIZE");
  return {
    name: "DMG script",
    status: supportsSigning ? "ok" : "warn",
    message: supportsSigning ? "signing-aware DMG script found" : "DMG script found without signing support",
    detail: supportsNotarization ? "notarization support detected" : undefined,
  };
}

function checkBuildOutput(root: string): DoctorCheck {
  const buildDir = join(root, "build");
  if (!existsSync(buildDir)) {
    return {
      name: "Build output",
      status: "warn",
      message: "build/ not found yet",
      detail: "Run the generated package manager build script before packaging.",
    };
  }

  const apps = findMatchingEntries(buildDir, ".app");
  const dmgs = findMatchingEntries(join(buildDir, "dmg"), ".dmg");
  return {
    name: "Build output",
    status: apps.length > 0 || dmgs.length > 0 ? "ok" : "warn",
    message: `${apps.length} app bundle(s), ${dmgs.length} dmg file(s)`,
  };
}

function findMatchingEntries(root: string, suffix: string): string[] {
  if (!existsSync(root)) {
    return [];
  }

  const results: string[] = [];
  walk(root);
  return results;

  function walk(current: string): void {
    let entries;
    try {
      entries = readdirSync(current, { withFileTypes: true });
    } catch {
      return;
    }

    for (const entry of entries) {
      const fullPath = join(current, entry.name);
      if (entry.name.endsWith(suffix)) {
        results.push(fullPath);
      }
      if (entry.isDirectory() && results.length < 50) {
        walk(fullPath);
      }
    }
  }
}
